WozUCoreDemo/Models/Customer.cs
namespace WozUCoreDemo.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

WozUCoreDemo/Models/WozUContext.cs
using Microsoft.EntityFrameworkCore;

namespace WozUCoreDemo.Models
{
    public class WozUContext : DbContext
    {
        public WozUContext(DbContextOptions<WozUContext> options) : base(options) { }

        public DbSet<Customer> Customers { get; set; }
    }
}

WozUCoreDemo/Controllers/CustomerController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WozUCoreDemo.Models;

namespace WozUCoreDemo.Controllers
{
    [Route("api/[controller]")]
    public class CustomerController : Controller
    {
        // Dependency injection to get the Database Context
        private WozUContext _context;
        public CustomerController(WozUContext context)
        {
            _context = context;
        }

        // Update to use the Database Context
        [HttpGet]
        public IActionResult GetAllCustomers()
        {
            var customers = _context.Customers.ToList();
            return base.Ok(customers);
        }

        // Use the Database Context
        [HttpGet("{id}")]
        public IActionResult GetCustomer(int id)
        {
            var customer = _context.Customers.FirstOrDefault(cust => cust.Id == id);
            if (customer != null)
            {
                return base.Json(customer);
            }
            return base.NotFound();
        }

        // Use the Database Context
        [HttpPost]
        public IActionResult AddCustomer([FromBody]Customer newCustomer)
        {
            if (newCustomer != null)
            {
                try
                {
                    _context.Customers.Add(newCustomer);
                    _context.SaveChanges();
                    return base.Created($"/{newCustomer.Id}", newCustomer);
                }
                catch (System.Exception ex)
                {
                    return base.StatusCode(500, ex.Message);
                }
            }
            return base.BadRequest();
        }

        // Use the Database Context
        [HttpPut("{id}")]
        public IActionResult UpdateCustomer(int id, [FromBody]Customer updatedCustomer)
        {
            var customer = _context.Customers.FirstOrDefault(cust => cust.Id == id);
            if (customer != null)
            {
                try
                {
                    customer.FirstName = updatedCustomer.FirstName;
                    customer.LastName = updatedCustomer.LastName;
                    customer.Email = updatedCustomer.Email;
                    _context.Update(customer);
                    _context.SaveChanges();
                    return base.NoContent();
                }
                catch (System.Exception ex)
                {
                    return base.BadRequest(ex.Message);
                }
            }
            return base.NotFound();
        }

        // Use the Database Context
        [HttpDelete("{id}")]
        public IActionResult DeleteCustomer(int id)
        {
            var customer = _context.Customers.FirstOrDefault(cust => cust.Id == id);
            if (customer != null)
            {
                _context.Customers.Remove(customer);
                _context.SaveChanges();
                return base.NoContent();
            }
            return base.NotFound();
        }
    }
}

WozUCoreDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WozUCoreDemo.Controllers
{
    [Route("api/[controller]/[action]")]
    public class HomeController : Controller
    {
        [HttpGet]
        public string Index() {
            return "Home";
        }

        [HttpGet("{value}")]
        public string Index(string value){
            return value;
        }

        [HttpPost]
        public string Post([FromBody]string value){
            return "Posted Value:" + value;
        }
    }
}

WozUCoreDemo/Controllers/HomePageController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WozUCoreDemo.Models;

namespace WozUCoreDemo.Controllers
{
    public class HomePageController : Controller
    {
        // Use dependency injection to get the database context
        private readonly WozUContext _context;
        public HomePageController(WozUContext context)
        {
            _context = context;
        }
        public IActionResult Index() {

            // Get a list of all the customers in the system.
            List<Customer> customers = _context.Customers.ToList();

            // Pass customers to the view
            return View(customers);
        }

        [HttpGet]
        public IActionResult Edit(int id){
            Customer customer = _context.Customers.FirstOrDefault(c => c.Id == id);
            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(Customer editedCustomer){
            Customer originalCustomer = _context.Customers.FirstOrDefault(c => c.Id == editedCustomer.Id);
            originalCustomer.FirstName = editedCustomer.FirstName;
            originalCustomer.LastName = editedCustomer.LastName;
            originalCustomer.Email = editedCustomer.Email;
            _context.Customers.Update(originalCustomer);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WozUCoreDemo/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WozUCoreDemo.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

WozUCoreDemo/Views/HomePage/edit.cshtml
@model Customer
<form asp-controller="HomePage" asp-action="Edit" asp-anti-forgery="true">
    <input type="hidden" value="@Model.Id" />
    <label asp-for="FirstName"></label><input asp-for="FirstName">
    <label asp-for="LastName"></label><input asp-for="LastName">
    <label asp-for="Email"></label><input asp-for="Email">
    <button type="submit">Save</button>
</form>

WozUCoreDemo/Views/HomePage/index.cshtml
@model List<Customer>
<h1>Home Index Page</h1>
<p>This page will be the default landing page.</p>

@foreach (var customer in Model)
{
    <div>
        <a asp-controller="HomePage" asp-action="Edit" asp-route-id="@customer.Id">
            <dl>
                <dt>First Name: </dt>
                <dd>@customer.FirstName</dd>
                <dt>Last Name:</dt>
                <dd>@customer.LastName</dd>
                <dt>Email:</dt>
                <dd>@customer.Email</dd>
            </dl>
        </a>
    </div>
}

WozUCoreDemo/Views/Shared/_Layout.cshtml
<!-- Create layout -->
<!DOCTYPE html>
<html>
    <head>
        <title>Home Index Page</title>
        <link 
            rel="stylesheet" 
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
            crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" asp-controller="HomePage" asp-action="Index">Home Page</a></li>
                    <li class="nav-item"><a class="nav-link" href="http://github.com">GitHub</a></li>
                </ul>
            </nav>
            <!-- Location to render the view called by the controller -->
            @RenderBody()
        </div>
    </body>
</html>